# Generated by Django 5.2.14 on 2026-05-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_code', models.CharField(blank=True, max_length=64, null=True)),
                ('common_name', models.CharField(max_length=256)),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=32, null=True)),
                ('drug_category', models.CharField(blank=True, max_length=64, null=True)),
                ('is_original', models.BooleanField(default=False)),
                ('is_first_drug', models.BooleanField(default=False)),
                ('is_overseas_medicine', models.BooleanField(default=False)),
                ('target', models.CharField(blank=True, max_length=256, null=True)),
                ('production_factory', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(default='readonly_db', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=256)),
                ('indication_points', models.JSONField(default=list)),
                ('specification_indication', models.TextField(blank=True, null=True)),
                ('month_drug_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_charity', models.BooleanField(default=False)),
                ('source', models.CharField(default='readonly_db', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
