# Generated by Django 5.2.14 on 2026-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_id_alter_drugindication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drugindication',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
