# Generated by Django 5.2.14 on 2026-05-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_drug_id_alter_drugindication_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugAuditPoint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('indication', models.CharField(max_length=256)),
                ('point_index', models.IntegerField(default=1)),
                ('point_content', models.TextField()),
                ('point_detail', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_points', to='drugs.drug')),
            ],
            options={
                'indexes': [models.Index(fields=['drug_id', 'indication'], name='drugs_druga_drug_id_806ff4_idx')],
            },
        ),
    ]
