# Generated by Django 5.2.14 on 2026-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
