# Generated by Django 5.2.14 on 2026-05-15 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0003_alter_calculationalgorithm_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_system', models.CharField(max_length=3)),
                ('source_case_no', models.CharField(blank=True, max_length=64, null=True)),
                ('insured_id', models.CharField(max_length=64)),
                ('insured_name', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=18)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('diagnosis', models.CharField(blank=True, default='', max_length=256)),
                ('hospital_name', models.CharField(blank=True, max_length=256, null=True)),
                ('report_date', models.DateTimeField(null=True)),
                ('risk_date', models.DateTimeField(null=True)),
                ('claim_mode', models.CharField(default='reimbursement', max_length=16)),
                ('claim_type', models.CharField(default='SP', max_length=32)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('priority_set_at', models.DateTimeField(null=True)),
                ('max_execution_minutes', models.IntegerField(default=120)),
                ('agent_started_at', models.DateTimeField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority_set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='policies.project')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('storage_path', models.CharField(max_length=512)),
                ('attachment_type', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=64)),
                ('upload_source', models.CharField(default='local', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_person_name', models.CharField(max_length=64)),
                ('insured_relation', models.CharField(blank=True, max_length=32, null=True)),
                ('report_person_phone', models.CharField(blank=True, default='', max_length=20)),
                ('report_person_sex', models.CharField(blank=True, max_length=4, null=True)),
                ('apply_claim_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='readonly_db', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_links', to='cases.case')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policy')),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['insured_id'], name='cases_case_insured_c3b091_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['project_id'], name='cases_case_project_54aa4b_idx'),
        ),
    ]
