# Generated by Django 5.2.14 on 2026-05-15 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('rules', '0003_alter_auditrule_id_alter_prompttemplate_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=32)),
                ('decision', models.CharField(blank=True, max_length=32, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('policy_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.policylink')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=64)),
                ('opinion', models.TextField()),
                ('action', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.auditresult')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='audit.auditresult')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rules.auditrule')),
            ],
        ),
        migrations.CreateModel(
            name='ToolCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64)),
                ('phase_type', models.CharField(max_length=64)),
                ('tool_name', models.CharField(max_length=64)),
                ('call_params_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('status', models.CharField(default='success', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['case_id', 'tool_name', 'call_params_hash'], name='audit_toolc_case_id_49e1ee_idx')],
            },
        ),
    ]
