# Generated by Django 5.2.14 on 2026-05-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationAlgorithm',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('algorithm_id', models.CharField(max_length=64)),
                ('algorithm_logic', models.TextField(blank=True, null=True)),
                ('algorithm_describe', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32)),
                ('ref_id', models.CharField(max_length=64)),
                ('limit_type', models.CharField(max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(default='readonly_db', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=256)),
                ('claim_type', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('project_code', models.CharField(max_length=64)),
                ('project_name', models.CharField(max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256, null=True)),
                ('project_type', models.CharField(blank=True, max_length=64, null=True)),
                ('claim_type', models.CharField(blank=True, max_length=64, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('project_status', models.CharField(default='0', max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('policy_no', models.CharField(max_length=64)),
                ('insured_id', models.CharField(max_length=64)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.project'),
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('insurance_code', models.CharField(max_length=64)),
                ('insurance_liability', models.CharField(blank=True, max_length=256, null=True)),
                ('duty_type', models.CharField(blank=True, max_length=64, null=True)),
                ('security_lines', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('deductible_excess', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('waiting_period', models.IntegerField(null=True)),
                ('algorithm_id', models.CharField(max_length=64, null=True)),
                ('pre_existing_disease_ratio', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('not_pre_existing_disease_ratio', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.product')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.project')),
            ],
        ),
    ]
