# Generated by Django 5.2.14 on 2026-05-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=64, unique=True)),
                ('rule_name', models.CharField(max_length=256)),
                ('rule_description', models.TextField(blank=True, null=True)),
                ('layer', models.IntegerField(default=2)),
                ('priority', models.IntegerField(default=0)),
                ('is_blocking', models.BooleanField(default=False)),
                ('liability_types', models.JSONField(default=list)),
                ('primary_model', models.CharField(default='qwen3.6-plus', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_code', models.CharField(max_length=64)),
                ('interface_type', models.CharField(max_length=64, null=True)),
                ('interface_name', models.CharField(max_length=256, null=True)),
                ('prompt_content', models.TextField()),
                ('primary_model', models.CharField(max_length=64, null=True)),
                ('backup_model', models.CharField(max_length=256, null=True)),
                ('versions', models.CharField(default='1', max_length=16)),
                ('effective', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('prompt_content', models.TextField()),
                ('primary_model', models.CharField(max_length=64, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.auditrule')),
            ],
        ),
    ]
