# Generated by Django 5.2.14 on 2026-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_auditrule_id_alter_prompttemplate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrule',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruleversion',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
